dist: trusty
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
